spring:
  application:
    name: MovieReservationSystem

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/MovieReservationSystem}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345678}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
    hibernate:
      ddl-auto: create
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB

jwt:
  secret: 553389489ac506c280ee6bdbf29ce71ba1f9a0d1dbd16bc1c2bfa13fb862a8db

server:
  servlet:
    context-path: '/api/'
  error:
    include-message: always
  port: ${PORT:8080}
  address: 0.0.0.0